services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
  postgres:
    image: postgres:latest
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
  solana_validator:
    build:
      context: .
      dockerfile: docker.solana.Dockerfile
    image: ff_solana
    profiles:
      - blockchain
    ports:
      - 8899:8899
      - 1024:1024
      - 1027:1027
      - 8900:8900
    entrypoint: ["solana-test-validator"]
    command:
      - "--ticks-per-slot"
      - "256"
      - "--limit-ledger-size"
      - "5000"