services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass

  solana_validator:
    build:
      context: .
      dockerfile: docker.solana.Dockerfile
    image: ff_solana
    profiles:
      - blockchain
    ports:
      - 8899:8899
      - 1024:1024
      - 1027:1027
      - 8900:8900
    volumes:
      - ./solana-cli.ci.yml:/usr/ff/solana-cli.ci.yml
      - ./solana_docker_entrypoint.sh:/usr/ff/entrypoint.sh
    healthcheck:
      test: [
        "CMD",
        "solana", "--config", "/usr/ff/solana-cli.ci.yml",
        "cluster-version", "--url", "http://localhost:8899"
      ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    entrypoint: ["/usr/ff/entrypoint.sh"]
    command:
      - "solana-test-validator"
      - "--ticks-per-slot"
      - "256"
      - "--limit-ledger-size"
      - "5000"

  solana_logs:
    build:
      context: .
      dockerfile: docker.solana.Dockerfile
    image: ff_solana
    depends_on:
      solana_validator:
        condition: service_healthy
    profiles:
      - blockchain
    network_mode: host
    volumes:
      - ./solana-cli.ci.yml:/usr/ff/solana-cli.ci.yml
    command:
      - "--config"
      - "/usr/ff/solana-cli.ci.yml"
      - "logs"
      - "--verbose"