services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass

  solana:
    build:
      context: .
      dockerfile: docker.solana.Dockerfile
    image: ff_solana
    profiles:
      - blockchain
    ports:
      - 8899:8899
      - 1024:1024
      - 1027:1027
      - 8900:8900
    volumes:
      - ./solana-cli.docker.yml:/usr/ff/solana-cli.docker.yml
      - ./solana_docker_entrypoint.sh:/usr/ff/entrypoint.sh
    healthcheck:
      test: [
        "CMD",
        "solana", "--config", "/usr/ff/solana-cli.docker.yml",
        "cluster-version", "--url", "http://localhost:8899"
      ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    entrypoint: ["/usr/ff/entrypoint.sh"]
    command:
      - "solana-test-validator"
      - "--ticks-per-slot"
      - "256"
      - "--limit-ledger-size"
      - "5000"

  solana_logs:
    build:
      context: .
      dockerfile: docker.solana.Dockerfile
    image: ff_solana
    depends_on:
      solana:
        condition: service_healthy
    profiles:
      - blockchain
    network_mode: host
    volumes:
      - ./solana-cli.docker.yml:/usr/ff/solana-cli.docker.yml
    command:
      - "--config"
      - "/usr/ff/solana-cli.docker.yml"
      - "logs"
      - "--verbose"

  deploy_solana_programs:
    build:
      context: .
      dockerfile: docker.anchor.Dockerfile
    image: ff_anchor
    depends_on:
      solana:
        condition: service_healthy
    profiles:
      - blockchain
    network_mode: host
    entrypoint: bash
    command: -c "solana airdrop 5 && anchor deploy --provider.wallet /root/.config/solana/id.json"

  extract_solana_program_keys:
    build:
      context: .
      dockerfile: docker.anchor.Dockerfile
    image: ff_anchor
    depends_on:
      solana:
        condition: service_healthy
    profiles:
      - blockchain
    network_mode: host
    volumes:
      - ./solana_program_keys:/usr/ff/solana_program_keys
      - ./solana_extract_program_keys.sh:/usr/ff/solana_extract_program_keys.sh
    entrypoint: bash
    command: >
      -c '
        anchor keys list > /usr/ff/program_keys.txt
        chmod +x /usr/ff/solana_extract_program_keys.sh
        /usr/ff/solana_extract_program_keys.sh /usr/ff/program_keys.txt /usr/ff/solana_program_keys/solana_program_keys.env
      '
