[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "HdxpgGmRXeUpXE2vVZZCy2a69Ypozs8YLt3LXPHRUkG6"

[provider]
cluster = "Localnet"
wallet = "../../../solana.id.json"

[scripts]
test = "node --run test"
