[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "HdxpgGmRXeUpXE2vVZZCy2a69Ypozs8YLt3LXPHRUkG6"
round = "5kS2nb5CSCVcdb4N7iA1kQuAZYKFttXagoHv2TxWmzg9"
username = "uMeQ3a2zVJf1pVa4uFu2Y6i88S3soEq3Q2aJjod3VD8"

[provider]
cluster = "localnet"
wallet = "../../../solana.id.json"

[scripts]
test = "node --run test"
