[toolchain]
# 1.88.0-nightly fixes the following issues during `anchor build`:
# https://github.com/solana-foundation/anchor/issues/3662
# https://github.com/solana-foundation/anchor/issues/3676
channel = "nightly-2025-04-22"
components = ["rustfmt", "clippy"]
profile = "minimal"